### ISSUE TITLE
question about how this works ?

### ISSUE THREAD

**Issue by joeblew99** [shurcooL/ivybrowser#1]
The main is identical (give or take) to robs, and makes sense.
https://github.com/robpike/ivy/blob/master/ivy.go

Its all running in the same app process. In other words Robs code is running in the browser.
But you have managed to get a io.reader / writer going between the ivy code and the frontend ?
Pretty cool technique..

**Comment by dmitshur** [comment]
I gave a talk about this just today at dotGo.

Everything browser-specific is in `io_js.go` file, take a look at that:

https://github.com/shurcooL/ivybrowser/blob/fa41648f09f2a74ebdbeaf8489b319bb5978e270/io_js.go#L14-L18

The video of my talk will be posted on http://www.thedotpost.com/ in a few weeks. I'll probably get the slides up pretty soon, they would also work to answer this question.

**Comment by dmitshur** [comment]
@joeblew99, that video has been posted by now:

https://www.youtube.com/watch?v=9XTl1d4nwdY

The part where I talk about implementing ivy to run in browser is from 3:22 to 9:13.

https://www.youtube.com/watch?v=9XTl1d4nwdY&t=322

**Comment by joeblew99** [comment]
thansk @shurcooL will check it out.
